version: '3.9'
services:
  frontend:
    container_name: app_frontend
    depends_on:
      backend:
        condition: service_healthy
    build: ./frontend
    environment:
      - REACT_APP_HOST=backend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    depends_on:
      db:
        condition: service_healthy
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    environment:
      - PORT=3001
      - MYSQLUSER=root
      - MYSQLPASSWORD=123456
      - MYSQLHOST=db
      - MYSQLPORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
       - ./backend/src:/app-backend/src
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE